[package]
name         = "nixploit"
version      = "0.1.0"
edition      = "2024"
rust-version = "1.98.1"
description  = "Nix vulnerability scanning"
license      = "EUPL-1.2"
publish      = false

[dependencies]
flate2      = "1.1.10"
hmac-sha256 = "1.1.15"
jiff        = { version = "0.2.37", default-features = false, features = [ "std" ] }
mimalloc    = "0.1.52"
misstep     = { version = "0.3.0", features = [ "pretty" ] }
pound       = "0.1.8"
prometheus  = { version = "0.14.0", default-features = false }
rusqlite    = { version = "0.40.2", features = [ "bundled" ] }
semver      = "1.0.28"
serde       = { version = "1.0.229", features = [ "derive" ] }
serde_json  = { version = "1.0.151", features = [ "raw_value" ] }
tempfile    = "3.27.0"
toml        = "1.1.6"
ureq        = { version = "3.4.2", default-features = false, features = [ "rustls", "json" ] }
zip         = { version = "8.6.0", default-features = false, features = [ "deflate-flate2" ] }

[dependencies.lz4_flex]
default-features = false
features         = [ "std", "safe-encode", "safe-decode", "checked-decode" ]
version          = "0.14.0"

[profile.release]
codegen-units = 1
lto           = "thin"
opt-level     = 3
panic         = "abort"
strip         = "symbols"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
cargo    = { level = "warn", priority = -1 }
nursery  = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

blanket_clippy_restriction_lints = "allow"
restriction                      = { level = "warn", priority = -1 }

arbitrary_source_item_ordering  = "allow"
arithmetic_side_effects         = "allow"
else_if_without_else            = "allow"
error_impl_error                = "allow"
exhaustive_enums                = "allow"
exhaustive_structs              = "allow"
implicit_return                 = "allow"
indexing_slicing                = "allow"
integer_division                = "allow"
integer_division_remainder_used = "allow"
missing_trait_methods           = "allow"
module_name_repetitions         = "allow"
question_mark_used              = "allow"
ref_patterns                    = "allow"
rest_pat_in_fully_bound_structs = "allow"
separated_literal_suffix        = "allow"
single_call_fn                  = "allow"
std_instead_of_alloc            = "allow"
std_instead_of_core             = "allow"
tests_outside_test_module       = "allow"
